import { useMemo } from 'react';
import { format } from 'date-fns';
import { useHarmonicsStore } from '@/stores/harmonicsStore';
import { useTimeStore } from '@/stores/timeStore';
import { predictTideSeries, findExtremes } from '@/lib/harmonics';

/**
 * PrintReport - renders hidden content that appears only when printing.
 * The print button is in ExportMenu.tsx.
 */
export function PrintReport() {
  const station = useHarmonicsStore((s) => s.selectedStation);
  const epoch = useTimeStore((s) => s.epoch);

  const tideData = useMemo(() => {
    if (!station) return { extremes: [], days: [] };

    const now = new Date(epoch);
    const start = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const end = new Date(start.getTime() + 7 * 24 * 60 * 60 * 1000); // 7 days

    const series = predictTideSeries(station, start, end, 10);
    const extremes = findExtremes(series);

    // Group by day
    const days: Map<string, typeof extremes> = new Map();
    for (const e of extremes) {
      const dayKey = format(e.time, 'yyyy-MM-dd');
      if (!days.has(dayKey)) {
        days.set(dayKey, []);
      }
      days.get(dayKey)!.push(e);
    }

    return {
      extremes,
      days: Array.from(days.entries()).map(([date, tides]) => ({
        date: new Date(date),
        tides,
      })),
    };
  }, [station, epoch]);

  if (!station) return null;

  return (
    <>
      {/* Print-only content */}
      <div className="hidden print:block print-report">
        <header className="print-header">
          <h1>Tide Predictions</h1>
          <h2>{station.name}{station.state ? `, ${station.state}` : ''}, {station.country}</h2>
          <p>
            Coordinates: {station.lat.toFixed(4)}°{station.lat >= 0 ? 'N' : 'S'},{' '}
            {Math.abs(station.lon).toFixed(4)}°{station.lon >= 0 ? 'E' : 'W'}
          </p>
          <p>Datum: {station.datum}</p>
          <p>Generated: {format(new Date(epoch), 'PPP p')}</p>
        </header>

        <main>
          <h3>7-Day Tide Schedule</h3>
          <table className="tide-table">
            <thead>
              <tr>
                <th>Date</th>
                <th>Time</th>
                <th>Type</th>
                <th>Height (m)</th>
              </tr>
            </thead>
            <tbody>
              {tideData.days.map((day) => (
                day.tides.map((tide, i) => (
                  <tr key={`${format(day.date, 'yyyy-MM-dd')}-${i}`}>
                    {i === 0 && (
                      <td rowSpan={day.tides.length} className="date-cell">
                        {format(day.date, 'EEE, MMM d')}
                      </td>
                    )}
                    <td>{format(tide.time, 'HH:mm')}</td>
                    <td className={tide.type === 'high' ? 'high-tide' : 'low-tide'}>
                      {tide.type === 'high' ? 'High' : 'Low'}
                    </td>
                    <td>{tide.height.toFixed(2)}</td>
                  </tr>
                ))
              ))}
            </tbody>
          </table>

          <footer className="print-footer">
            <p>
              <strong>Note:</strong> These predictions are calculated using harmonic analysis.
              Actual tide heights may vary due to weather conditions, atmospheric pressure,
              and other factors.
            </p>
            <p className="attribution">
              Generated by Tidal Harmonics Visualizer
            </p>
          </footer>
        </main>
      </div>
    </>
  );
}
